// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratosTest/internal/biz"
	"kratosTest/internal/conf"
	"kratosTest/internal/data"
	"kratosTest/internal/server"
	"kratosTest/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewRedis(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	myKratosRepo := data.NewMyKratosRepo(dataData, logger)
	myKratosUsecase := biz.NewMyKratosUsecase(myKratosRepo, logger)
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	myKratosService := service.NewMyKratosService(myKratosUsecase, greeterUsecase)
	httpServer := server.NewHTTPServer(confServer, myKratosService, logger)
	grpcServer := server.NewGRPCServer(confServer, myKratosService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
